<a href="https://colab.research.google.com/github/rmbgatram/DAA-Solutions/blob/main/numpy_array_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy Examples**

**Creating 0D ndarray**

In [ ]:
import numpy as np
a = np.array(10)
print('0D Array elements: ', a)
print('Dimension of a: ', a.ndim)
print('size of a: ', a.size)
print(type(a))

0D Array elements:  10
Dimension of a:  0
size of a:  1
<class 'numpy.ndarray'>


**Creating 1D ndarray & accessing individual elements**
* a[index]
* starting index is 0
* -ve index gives elements from end

In [ ]:
import numpy as np
# Creating array using list
a = np.array([1, 2, 3, 4, 5]) 
# Creating array using tuple
b = np.array((1, 2, 3, 4, 5, 6)) 
# Prints Dimesion of a and b
print('Dimension of a: ', a.ndim)
print('Dimension of b: ', b.ndim)
# Prints size of a and b
print('Size of a: ', a.size)
print('Size of b: ', b.size)
# Prints Elements of a and b
print('1D Array Elements of a: ', a)
print('1D Array Elements of b: ', b)
# individual elements are accessed with index, index starts from 0
# negative index to access elements from the end
print('2nd Element of a: ', a[1]) 
print('3rd Element of b: ', b[2]) 
print('2nd Element of b from end: ', b[-2]) 


Dimension of a:  1
Dimension of b:  1
Size of a:  5
Size of b:  6
1D Array Elements of a:  [1 2 3 4 5]
1D Array Elements of b:  [1 2 3 4 5 6]
2nd Element of a:  2
3rd Element of b:  3
2nd Element of b from end:  5


**Creating 2D ndarray & accessing individual elements**
* a[rindex, cindex]
* starting index is 0
* -ve index gives elements from end

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print('Dimension of a: ', a.ndim)
print('Size of a: ', a.size)
print('2D Array Elements: ', a)
print('a[1,1] Element: ', a[1,1])

Dimension of a:  2
Size of a:  6
2D Array Elements:  [[1 2 3]
 [4 5 6]]
a[1,1] Element:  5


**Creating 3D ndarray & accessing individual elements**

In [ ]:
import numpy as np
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print('3D Array Elements: ', a)
print('Dimension of a: ', a.ndim)
# first index signifies which matrix, second index signifies which array and third index signifies which element.
print('a[0,1,2] Element: ', a[0,1,2])

3D Array Elements:  [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension of a:  3
a[0,1,2] Element:  6


**Array Slicing**


*   a[start: end]
*   a[start: end: step]
* If we don't pass start its considered 0
* If we don't pass end its considered length of array in that dimension
* If we don't pass step its considered 1


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('Elements from 2 to 5: ', a[1:5])
print('Elements from start to 4: ', a[:4])
print('Elements from 2 to end: ', a[2:])
print('Elements from start to end with step 2: ', a[::2])
print('Elements from end to second: ', a[-3:-1])

b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Elements of b: ', b)
print('Elements first row from 2 to 4 of b : ', b[1,2:4])
print('Elements 0 to 2 row from 1 to 4 columns of b : ', b[0:2, 1:4])

Elements from 2 to 5:  [2 3 4 5]
Elements from start to 4:  [1 2 3 4]
Elements from 2 to end:  [ 3  4  5  6  7  8  9 10]
Elements from start to end with step 2:  [1 3 5 7 9]
Elements from end to second:  [8 9]
Elements of b:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Elements first row from 2 to 4 of b :  [8 9]
Elements 0 to 2 row from 1 to 4 columns of b :  [[2 3 4]
 [7 8 9]]


**Data Types**
* To know datatype of the array with a.dtype
* Creating array with defined datatype: arr = np.array([1, 2, 3, 4], dtype='S')
* List of Datatypes in NumPy: i - integer, b - boolean, u - unsigned integer, f - float, c - complex float, m - timedelta, M - datetime, O - object, S - string, U - unicode string, V - fixed chunk of memory for other type ( void )
* The astype(datatype) function creates a copy of the array, and allows you to specify the data type as a parameter. (*a.astype('i') or a.astype(int)*)

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print('Datatype of a: ', a.dtype)

b = np.array(['ram', 'kiran', 'sonu'])
print('Datatype of b: ', b.dtype)

c = np.array([10.5, 6, 11.5, 33], dtype='f')
print('Elements of c:', c)
print('Datatype of c:', c.dtype)

d = np.array([1.1, 2.1, 3.1])
e = d.astype('i') # or d.astype(int)
f = d.astype(bool)
print('Elements of d: ', d)
print('Elements of e: ', e)
print('Elements of f: ', f)


Datatype of a:  int64
Datatype of b:  <U5
Elements of c: [10.5  6.  11.5 33. ]
Datatype of c: float32
Elements of d:  [1.1 2.1 3.1]
Elements of e:  [1 2 3]
Elements of f:  [ True  True  True]


**Copy and View**
b = a.copy()
c = a.view()
* Difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print('Elements of a: ', a)

b = a.copy()
print('Elements of b: ', b)
print('Base of b: ', b.base)

c = a.view()
print('Elements of c: ', c)
print('Base of c: ', c.base)


Elements of a:  [1 2 3 4 5 6]
Elements of b:  [1 2 3 4 5 6]
Base of b:  None
Elements of c:  [1 2 3 4 5 6]
Base of c:  [1 2 3 4 5 6]


**Shape and Reshpae of an Array**
* The a.shape of an array is the number of elements in each dimension.
* a.reshape(sizes) Reshaping means changing the shape of an array.
* Flattening array means converting a multidimensional array into a 1D array. b = a.reshape(-1)

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print('Shape of the a:', a.shape)

b = np.array([1, 2, 3, 4], ndmin=5)
print('Shape of the b:', b.shape)

c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
d = c.reshape(4, 3) # 2D Array
print(d)
e = c.reshape(2, 3, 2) #3D Array
print(e)

f = np.array([[1, 2, 3], [4, 5, 6]])
g = f.reshape(-1)
print(g)

Shape of the a: (2, 4)
Shape of the b: (1, 1, 1, 1, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[1 2 3 4 5 6]


**Iterating Elements**
* Iterating means going through elements one by one.
* The function nditer() is a helping function that can be used from very basic to very advanced iterations. use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating. need to set flags=['buffered'] to perform this action.

for x in np.nditer(a, flags=['buffered'], op_dtypes=['S']):
  print(x)
* Iterating With Different Step Size

for x in np.nditer(arr[:, ::2]):
  print(x)

* index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
import numpy as np
# iterating 1D Array
a = np.array([1, 2, 3])
for x in a:
  print(x)

for x in np.nditer(a):
  print(x)

# with index
for idx, x in np.ndenumerate(a):
  print(idx, x)

# iterating 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
# row wise display
for x in b:
  print(x)
# element wise display
for x in b:
  for y in x:
    print(y)
# Iterating Arrays Using nditer()
for x in np.nditer(b):
  print(x)
for idx, x in np.ndenumerate(b):
  print(idx, x)
# Iterating Arrays Using nditer()
for x in np.nditer(b):
  print(x)
#Iterating Array With Different Data Types
for x in np.nditer(b, flags=['buffered'], op_dtypes=['S']):
  print(x)

# Iterating With Different Step Size
for x in np.nditer(b[:, ::2]):
  print(x)

# iterating 3D Array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in c:
  print(x)

for x in c:
  for y in x:
    for z in y:
      print(z)

for x in np.nditer(c):
  print(x)

1
2
3
1
2
3
(0,) 1
(1,) 2
(2,) 3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
1
2
3
4
5
6
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
1
3
4
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


**Joining Array**
* pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.
* stack() method along with the axis. If axis is not explicitly passed it is taken as 0.
* hstack() to stack along rows.

In [ ]:
import numpy as np
#Joining in the same axis
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.concatenate((a1, a2))
print('concatenation to two arrays: ')
print(a3)

# Joining with axis=1
b1 = np.array([[1, 2], [3, 4]])
b2 = np.array([[5, 6], [7, 8]])
b3 = np.concatenate((b1, b2), axis=1)
print('Joining two 2D arrays with axis=1: ')
print(b3)

# Stack order join
c1 = np.array([1, 2, 3])
c2 = np.array([4, 5, 6])
c3 = np.stack((c1, c2), axis=1)
print('stacking 1d arrays with axis=1: ')
print(c3)

# Stacking along with cols
d1 = np.array([1, 2, 3])
d2 = np.array([4, 5, 6])
d3 = np.hstack((d1, d2))
d4 = np.vstack((d1, d2))
d5 = np.dstack((d1, d2))
print('hstack: ')
print(d3)
print('vstack: ')
print(d4)
print('dstack: ')
print(d5)


concatenation to two arrays: 
[1 2 3 4 5 6]
Joining two 2D arrays with axis=1: 
[[1 2 5 6]
 [3 4 7 8]]
stacking 1d arrays with axis=1: 
[[1 4]
 [2 5]
 [3 6]]
hstack: 
[1 2 3 4 5 6]
vstack: 
[[1 2 3]
 [4 5 6]]
dstack: 
[[[1 4]
  [2 5]
  [3 6]]]


**Splitting NumPy Arrays**
* use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
* An alternate solution is using hsplit() opposite of hstack()


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array_split(a, 3)
print(b)
print(b[0])
print(b[1])
print(b[2])

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
b = np.array_split(a, 3)
print(b)

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
b = np.array_split(a, 3, axis=1)
print(b)



[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**Searching Arrays**
* To search an array, use the where() method.
* searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 4, 4])
# find where the indexes of 4
x = np.where(a == 4)
print(x)

# find even values from array
x = np.where(a%2 == 0)
print(x)

# binary search
a = np.array([1, 2, 3, 4, 5, 6, 7])
x = np.searchsorted(a, 4)
print(x)

# search from right side
x = np.searchsorted(a, 5, side='right')
print(x)

# search multiple values
a = np.array([1, 3, 5, 7])
x = np.searchsorted(a, [2, 4, 6])
print(x)



(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
3
5
[1 2 3]


**Sorting Arrays**

In [ ]:
import numpy as np
a = np.array([3, 2, 0, 1])
b = np.sort(a)
print(b)

a = np.array(['banana', 'cherry', 'apple'])
print(np.sort(a))

a = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(a))

a = np.array([41, 42, 43, 44])
x = [True, False, True, False]
b = a[x]
print(b)

fa = a > 42
b = a[fa]
print(fa)
print(b)

fa = a % 2 == 0
b = a[fa]
print(fa)
print(b)





[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]
[41 43]
[False False  True  True]
[43 44]
[False  True False  True]
[42 44]
